<?php

namespace ActivityBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findType($typeActivite)
    {
        $query=$this->getEntityManager()->createQuery("select a from ActivityBundle:Activity a where a.typeactivite='$typeActivite'");
        return $query->getResult();
    }
}
